language: python

node_js:
  - "5"

python:
  - 3.5.1

before_install:
  - npm install

install:
  - pip install cython
  - pip install git+https://github.com/quantmind/pulsar.git@master#egg=pulsar
  - pip install -r requirements-dev.txt

services:
  - redis-server

addons:
  postgresql: "9.4"

before_script:
  - psql -U postgres -f tests/db.sql
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - python setup.py test --coverage -q
  - flake8
  - npm test
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5.1' ]]; then python setup.py test --coveralls; fi

notifications:
  email: false

# Only test master and dev
branches:
  only:
    - master
    - dev
