language: python

python:
  - "3.4"

before_install:
  - npm install -g grunt-cli

install:
  - pip install -r requirements_dev.txt --use-mirrors
  - python setup.py install
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then npm install; fi

script:
  - grunt jasmine
  - pep8
  - sudo rm -rf lux
  - python -m runtests --coverage
  - python -m runtests --coveralls

notifications:
  email: false

# Only test master and dev
branches:
  only:
    - master
    - dev
