language: python

sudo: required
dist: trusty

python:
  - 3.5.2
  - 3.6-dev

services:
  - redis-server

install:
  - pip install -U -r requirements-dev.txt


addons:
  postgresql: "9.5"


before_script:
  - psql -U postgres -f tests/db.sql

script:
  - python setup.py test --coverage -q
  - flake8
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5.2' ]]; then python setup.py test --coveralls; fi

notifications:
  email: false
