language: python

sudo: false

python:
  - "3.4"

before_install:
  - echo "deb http://download.rethinkdb.com/apt `lsb_release -cs` main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - apt-get update -qq
  - apt-get install rethinkdb
  - npm install -g grunt-cli

install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements_pre.txt
  - python setup.py install
  - rm -rf build
  - rm -rf lux.egg-info
  - npm install

before_script:
  - rethinkdb --io-threads 2048 --daemon
  - ulimit -S -n 2048
  - sleep 5
  - psql -U postgres -c "CREATE USER lux WITH PASSWORD 'luxtest';"
  - psql -U postgres -c "CREATE USER lux CREATEDB;"
  - psql -U postgres -c "CREATE DATABASE luxtests;"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE luxtests to lux;"

script:
  - grunt jasmine
  - pep8
  - rm -rf lux
  - python -m runtests --coverage --test-timeout 10
  - python -m runtests --coveralls

after_script:
  - killall rethinkdb

notifications:
  email: false

# Only test master and dev
branches:
  only:
    - master
    - dev
