language: python

python:
  - 3.5.2

services:
  - redis-server

install:
  - pip install -r requirements-dev.txt

addons:
  postgresql: "9.4"

script:
  - python setup.py test --coverage -q
  - flake8
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5.2' ]]; then python setup.py test --coveralls; fi

notifications:
  email: false
