application: quantmindblog
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Static assets
- url: /media/blogapp
  static_dir: blogapp/media/blogapp
- url: /media/lux
  static_dir: site-packages/lux/media/lux
- url: /favicon\.ico
  static_files: blogapp/media/blogapp/favicon.ico
  upload: /favicon.ico

# Web handlers
- url: /.*
  script: engine.app
  secure: always

libraries:
- name: ssl
  version: latest
- name: pycrypto
  version: latest