application: quantmindblog
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Static assets
- url: /media/potatoblog
  static_dir: potatoblog/media/potatoblog
- url: /media/lux
  static_dir: site-packages/lux/media/lux
- url: /favicon\.ico
  static_files: potatoblog/media/potatoblog/favicon.ico
  upload: /favicon.ico

# Web handlers
- url: /.*
  script: potatoengine.app
  secure: always

libraries:
- name: ssl
  version: latest
- name: pycrypto
  version: latest